name: metron
description: Metron Event Management Flutter App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  image_picker: ^1.0.4
  fluttertoast: ^8.2.4
  intl: ^0.19.0

flutter:
  uses-material-design: true
