name: metron
description: Metron Event Management Flutter App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^3.0.0
  flutter_secure_storage: ^8.1.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^2.0.0
  image_picker: ^0.9.8
  fluttertoast: ^8.2.0

flutter:
  uses-material-design: true
